env:
  node: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns: [
  node_modules/,
  client/,
  dist/,
  .eslintrc.yml,
  .prettierrc.yml,
  .gitignore,
  .github/,
  .vscode/,
  .huskyrc.yml,
  .lintstage
]
rules: {
  semi: [error, never],
  quotes: [error, single],
  indent: [error, 2],
  no-unused-vars: [warn],
  no-undef: [warn],
  no-mixed-spaces-and-tabs: [error],
  no-trailing-spaces: [error],
  no-multiple-empty-lines: [error],
  no-multi-spaces: [error]
}
